version: '3'
services:
  web-backend:
    build: web-backend/
    ports:
      - "8000:8000"
    volumes:
      - "./web-backend:/app"
    environment:
        AWS_ACCESS_KEY_ID: p1CsWchkAo9df4s68g7y
        AWS_SECRET_ACCESS_KEY: d76yDfnxC0nyjG7jm5j3mHcHZ0KePH8jt7Ant8Y2

  web-frontend:
    build: web-frontend/
    ports:
      - "80:80"
    environment:
      CUSTOM_SERVER_CONFIG: "
          location /api {
              proxy_pass http://web-backend:8000/api;
          }
      "

  edge:
    build: edge/
    ports:
      - "5000:5000"  # edge-master
      - "5050:5050"  # inference-service
      - "5100:5100"  # deterrent-service
    volumes:
      - "./edge:/app"
    devices:
     - /dev/video0:/dev/video0
