version: '3'
services:
  web-backend:
    build: web-backend/
    ports:
      - "8000:8000"
    volumes:
      - "./web-backend/requirements.txt:/requirements.txt"

  edge:
    build: edge/
    ports:
      - "5000:5000"  # edge-master
      - "5050:5050"  # inference-service
      - "5100:5100"  # deterrent-service
    volumes:
      - "./edge/requirements.txt:/requirements.txt"
    devices:
      - /dev/video0:/dev/video0
