FROM python:3.7

RUN mkdir /app
RUN mkdir -p /app/web-frontend/assets/images/sample_pests

COPY  . /app

WORKDIR /app

RUN pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_x86_64.whl

CMD [ "sh", "-c",  "pip install -r requirements.txt && python edge-master/edge_master_simulator_app.py" ]
